version: '3.8'

services:
  app-bus-girona:
    image: miquelroca08/app-bus-girona:v1.6.4
    build: .
    container_name: app-bus-girona
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      # Montamos la carpeta ./libs para poder actualizar los archivos GTFS sin reconstruir el contenedor
      - ./libs:/app/libs
    environment:
      - TMG_DEBUG=1
      - TZ=Europe/Madrid